<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <!-- Turn on R2R and composite for release -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishReadyToRunComposite>true</PublishReadyToRunComposite>
    <!-- Add option -->
    <!-- <PublishReadyToRunEmitSymbols>true</PublishReadyToRunEmitSymbols> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.6" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5" />
    <PackageReference Include="Spectre.Console" Version="0.49.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Polly.Extensions.Http" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.MassTransit\Liberty.MassTransit.csproj" />
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.SentrySelfHosted\Liberty.SentrySelfHosted.csproj" />
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.Serilog\Liberty.Serilog.csproj" />
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.ServiceDefaults\Liberty.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\modules\Liberty.Reservation.Application\Liberty.Reservation.Application.csproj" />
    <ProjectReference Include="..\Liberty.Reservation.Manager.Application\Liberty.Reservation.Manager.Application.csproj" />
    <ProjectReference Include="..\Liberty.Reservation.Manager.Distribution.WebAPI.Application\Liberty.Reservation.Manager.Distribution.WebAPI.Application.csproj" />
  </ItemGroup>

</Project>
