services:
  liberty-reservation-db:
    container_name: liberty-reservation-db
    image: postgres:16.4
    environment:
      POSTGRES_DB: liberty_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01j6efde8q4q48crxe93crwxkc
      READONLY_USER: user_facility_readonly
      READONLY_PASSWORD: 01jj10kbc1pgxw6hchebqaqqv0
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - ./db/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - liberty-db-data:/var/lib/postgresql/data
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'   # Use up to 0.5 CPU core on M4 Pro (equivalent to 1 ACU)
          memory: 2048M # Limit memory usage to 2 GiB (equivalent to 1 ACU)
        reservations:
          cpus: '0.25'  # Reserve at least 0.25 CPU core on M4 Pro
          memory: 1024M # Reserve at least 1 GiB RAM (~0.5 ACU)

  liberty-reservation-pgadmin4:
    container_name: liberty-reservation-pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@liberty.com
      PGADMIN_DEFAULT_PASSWORD: admin.liberty
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1

  liberty-reservation-redis:
    container_name: liberty-reservation-redis
    image: redis:7.4.0
    command: /bin/sh -c "redis-server --requirepass 01j6efde8q4"
    restart: unless-stopped
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'   # Use up to 0.5 CPU core on M4 Pro (equivalent to 1 ACU)
          memory: 2048M # Limit memory usage to 2 GiB (equivalent to 1 ACU)
        reservations:
          cpus: '0.25'  # Reserve at least 0.25 CPU core on M4 Pro
          memory: 1024M # Reserve at least 1 GiB RAM (~0.5 ACU)

  liberty-reservation-redis-commander:
    container_name: liberty-reservation-redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: unless-stopped
    environment:
      HTTP_USER: admin@liberty.com
      HTTP_PASSWORD: admin.liberty
      REDIS_HOSTS: liberty-reservation-redis:6379,password=01j6efde8q4
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1

  liberty-reservation-seq:
    image: datalust/seq
    container_name: liberty-reservation-seq
    environment:
      ACCEPT_EULA: Y
      SEQ_API_KEY: "01jErQ4kB7D11e78TyX92WqBN8"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    networks:
      - liberty-system
    volumes:
      - liberty-seq-data:/data

  liberty-reservation-minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9010:9000"                       # MinIO Console
      - "9011:9001"                       # MinIO Management Console
    environment:
      MINIO_ROOT_USER: minioadmin         # Root username
      MINIO_ROOT_PASSWORD: minioadmin123  # Root password
    volumes:
      - liberty-minio-data:/data                  # Persistent data storage
    command: server /data --console-address ":9011"

  liberty-reservation-db-migration:
    platform: linux/amd64
    container_name: liberty-reservation-db-migration
    image: ${REGISTRY:-liberty}/reservation/db-migration:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/modules/Liberty.Reservation.DbMigration/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationName: "liberty-reservation-db-migration"
      App_Name: "Liberty.Reservation.DbMigration"
      App_Version: "0.0.1"
      ConnectionStrings__MigrationsAssembly: "Liberty.Reservation.DbMigration"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      liberty-reservation-db:
        condition: service_healthy

  liberty-reservation-employee-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-employee-webapi
    image: ${REGISTRY:-liberty}/reservation/employee-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/employee/Liberty.Reservation.Employee.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3001
      # ASPNETCORE_URLS: http://+:3001;https://+:13001
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-employee-webapi"
      App_Name: "Liberty.Reservation.Employee.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Emp:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__MembershipFacilityService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      FaxImo__ApiUrl: "https://rest.faximo.jp/faximo/v2/request.json"
      FaxImo__RetryNum: 3
      FaxImo__UserName: "liberty"
      FaxImo__UserKey: "liberty-reservation"
      FaxImo__Password: ""
    restart: unless-stopped
    ports:
      - "3001:3001"
      # - "13001:13001"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-manager-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-manager-webapi
    image: ${REGISTRY:-liberty}/reservation/manager-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/manager/Liberty.Reservation.Manager.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3003
      # ASPNETCORE_URLS: http://+:3003;https://+:13003
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-manager-webapi"
      App_Name: "Liberty.Reservation.Manager.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Mng:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__ReservationEmployeeService__Url: "http://liberty-reservation-employee-webapi:3001"
      Services__ReservationEmployeeService__AccessCode: "01j531d4hct3k03h9c4zgptkq8"
      Services__MembershipFacilityService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      GMOPayment__Enabled: "true"
      GMOPayment__PaymentHost: "https://pt01.mul-pay.jp/payment"
      GMOPayment__ShopID: "tshop00070472"
      GMOPayment__ShopPassword: ""
      Services__BatchSchedulerService__Url: "http://liberty-batch-scheduler:3144"
      Services__BatchSchedulerService__AccessCode: "01JAPEP5KQ5E7B0TDSD47YR7ZS"
      MailTemplate__ApplicationName: "Plan Reservation System. Liberty co,.ltd"
      MailTemplate__ManagerURL: "http:/fe.manager.local.com/reservation/detail/{id}?facilityCode={facilityCode}"
      MailTemplate__UserURL: "http://fe.user.local.com/booking-history/edit/{id}"
      MailTemplate__GuestURL: "http://fe.user.local.com/guest/{guestCode}"
    restart: always
    ports:
      - "3003:3003"
      # - "13003:13003"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-manager-distribution-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-manager-distribution-webapi
    image: ${REGISTRY:-liberty}/reservation/manager-distribution-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/manager/Liberty.Reservation.Manager.Distribution.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3303
      # ASPNETCORE_URLS: http://+:3003;https://+:13303
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-manager-distribution-webapi"
      App_Name: "Liberty.Reservation.Manager.Distribution.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      MessageQueueSettings__QueueType: "RabbitMq"
      MessageQueueSettings__RabbitMqOptions__Url: "amqp://liberty-batch-rabbitmq"
      MessageQueueSettings__RabbitMqOptions__UserName: "guest"
      MessageQueueSettings__RabbitMqOptions__Password: "guest"
      Redis__Enabled: "false"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Mng:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__MembershipFacilityService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      Services__SiteService__GrpcUrl: "http://liberty-reservation-site-webapi:3004"
    restart: always
    ports:
      - "3303:3303"
      # - "13003:13003"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-manager-file-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-manager-file-webapi
    image: ${REGISTRY:-liberty}/reservation/manager-file-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/manager/Liberty.Reservation.Manager.File.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3006
      # ASPNETCORE_URLS: http://+:3006;https://+:13006
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-manager-file-webapi"
      App_Name: "Liberty.Reservation.Manager.File.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Mng:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__ReservationEmployeeService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      AmazonS3__AccessKeyId: ""
      AmazonS3__SecretAccessKey: ""
      AmazonS3__Region: ""
      AmazonS3__BucketName: "liberty-reservation"
    restart: always
    ports:
      - "3006:3006"
      # - "13006:13006"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-manager-webapi
      - liberty-reservation-seq

  liberty-reservation-site-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-site-webapi
    image: ${REGISTRY:-liberty}/reservation/site-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/site/Liberty.Reservation.Site.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3004
      # ASPNETCORE_URLS: http://+:3004;https://+:13004
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-site-webapi"
      App_Name: "Liberty.Reservation.Site.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=15;Connection Idle Lifetime=300;"
      Services__MembershipFacilityService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=15;Connection Idle Lifetime=300;"
      ConnectionPool__MaximumNumberOfConcurrentEntries: 50
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Site:"
      Redis__SlidingExpirationInSecond: "6000"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      SecretKey__HmacSecretKey: "LibertyHmacSecretKey12345"
      Services__BatchSchedulerService__Url: "http://liberty-batch-scheduler:3144"
      Services__BatchSchedulerService__AccessCode: "01JAPEP5KQ5E7B0TDSD47YR7ZS"
      MailTemplate__ApplicationName: "Plan Reservation System. Liberty co,.ltd"
      MailTemplate__ManagerURL: "http://fe.manager.local.com/reservation/detail/{id}?facilityCode={facilityCode}"
      MailTemplate__UserURL: "http://fe.user.local.com/booking-history/{id}"
      MailTemplate__GuestURL: "http://fe.user.local.com/{siteCode}/{facilityCode}/plan-reservation/email-verified/{guestCode}"
    restart: always
    ports:
      - "3004:3004"
      # - "13004:13004"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 1024M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-site-file-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-site-file-webapi
    image: ${REGISTRY:-liberty}/reservation/site-file-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/site/Liberty.Reservation.Site.File.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3007
      # ASPNETCORE_URLS: http://+:3007;https://+:13007
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-site-file-webapi"
      App_Name: "Liberty.Reservation.Site.File.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Site:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__ReservationEmployeeService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      AmazonS3__AccessKeyId: ""
      AmazonS3__SecretAccessKey: ""
      AmazonS3__Region: ""
      AmazonS3__BucketName: "liberty-reservation"
    restart: always
    ports:
      - "3007:3007"
      # - "13007:13007"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-site-webapi
      - liberty-reservation-seq

  liberty-reservation-user-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-user-webapi
    image: ${REGISTRY:-liberty}/reservation/user-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/user/Liberty.Reservation.User.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3002
      # ASPNETCORE_URLS: http://+:3002;https://+:13002
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-user-webapi"
      App_Name: "Liberty.Reservation.User.WebApi"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:User:"
      Redis__SlidingExpirationInSecond: "3600"
      Identity__Jwt__Authority: ""
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      Services__ReservationEmployeeService__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_facility;User id=postgres;Pwd=;"
      GMOPayment__Enabled: "true"
      GMOPayment__PaymentHost: "https://pt01.mul-pay.jp/payment"
      GMOPayment__ShopID: "tshop00070472"
      GMOPayment__ShopPassword: ""
      GMOPayment__RetUrl: "http://liberty-reservation-user-webapi:3002/gmo-payment-result"
      GMOPayment__CompleteUrl: "http://liberty-reservation-user-webapi:3002/gmo-payment-result"
      GMOPayment__CancelUrl: "http://liberty-reservation-user-webapi:3002/gmo-payment-result"
      GMOPayment__RedirectUserUrl: "http://fe.user.local.com/payment-result/{0}?codeInfo=resultCode"
      GMOPayment__RedirectSiteUrl: "http://fe.site.local.com/{0}/{1}/payment-result/{2}?codeInfo=resultCode"
      Services__BatchSchedulerService__Url: "http://liberty-batch-scheduler:3144"
      Services__BatchSchedulerService__AccessCode: "01JAPEP5KQ5E7B0TDSD47YR7ZS"
      MailTemplate__ApplicationName: "Plan Reservation System. Liberty co,.ltd"
      MailTemplate__ManagerURL: "http://fe.manager.local.com/reservation/detail/{id}?facilityCode={facilityCode}"
      MailTemplate__UserURL: "http://fe.user.local.com/booking-history/edit/{id}"
      MailTemplate__GuestURL: "http://fe.user.local.com/guest/{guestCode}"
    restart: unless-stopped
    ports:
      - "3002:3002"
      # - "13002:13002"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-user-file-webapi:
    platform: linux/amd64
    container_name: liberty-reservation-user-file-webapi
    image: ${REGISTRY:-liberty}/reservation/user-file-webapi:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/user/Liberty.Reservation.User.File.WebAPI/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3005
      # ASPNETCORE_URLS: http://+:3005;https://+:13005
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-user-file-webapi"
      App_Name: "Liberty.Reservation.User.File.WebApi"
      App_Version: "0.0.1"
      Identity__Jwt__Authority: ""
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Identity__AccessCode__Code: "01j531d4hct3k03h9c4zgptkq8"
      AmazonS3__AccessKeyId: ""
      AmazonS3__SecretAccessKey: ""
      AmazonS3__Region: ""
      AmazonS3__BucketName: "liberty-reservation"
    restart: unless-stopped
    ports:
      - "3005:3005"
      # - "13005:13005"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-user-webapi
      - liberty-reservation-seq

  liberty-reservation-mail-worker:
    platform: linux/amd64
    container_name: liberty-reservation-mail-worker
    image: ${REGISTRY:-liberty}/reservation/mail-worker:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/mail/Liberty.Reservation.Mail.Worker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3014
      # ASPNETCORE_URLS: http://+:3014;https://+:13014
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-mail-worker"
      App_Name: "Liberty.Reservation.Mail.Worker"
      App_Version: "0.0.1"
      Redis__Enabled: "true"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Mail:"
      Redis__SlidingExpirationInSecond: "3600"
      MessageQueueSettings__QueueType: "RabbitMq"
      MessageQueueSettings__RabbitMqOptions__Url: "amqp://liberty-batch-rabbitmq"
      MessageQueueSettings__RabbitMqOptions__UserName: "guest"
      MessageQueueSettings__RabbitMqOptions__Password: "guest"
      FaxImo__ApiUrl: "https://rest.faximo.jp/faximo/v2/request.json"
      FaxImo__RetryNum: 3
      FaxImo__UserName: "liberty"
      FaxImo__UserKey: "liberty-reservation"
      FaxImo__Password: ""
    restart: always
    ports:
      - "3014:3014"
      # - "13014:13014"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

  liberty-reservation-booking-worker:
    platform: linux/amd64
    container_name: liberty-reservation-booking-worker
    image: ${REGISTRY:-liberty}/reservation/booking-worker:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: src/services/booking/Liberty.Reservation.Booking.Worker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:3013
      # ASPNETCORE_URLS: http://+:3013;https://+:13013
      # ASPNETCORE_Kestrel__Certificates__Default__Password: liberty123!@
      # ASPNETCORE_Kestrel__Certificates__Default__Path: /app/Certs/liberty.pfx
      ApplicationName: "liberty-reservation-booking-worker"
      App_Name: "Liberty.Reservation.Booking.Worker"
      App_Version: "0.0.1"
      ConnectionStrings__DataContextConnection: "Server=liberty-reservation-db;Port=5432;Database=liberty_reservation;User id=postgres;Pwd=;"
      SerilogLogging__WriteToSeq__Enabled: "true"
      SerilogLogging__WriteToSeq__Url: "http://liberty-reservation-seq:80"
      SerilogLogging__WriteToSeq__ApiKey: "01jErQ4kB7D11e78TyX92WqBN8"
      Redis__Enabled: "true"
      Redis__UrlConfiguration: "liberty-reservation-redis:6379,password=01j6efde8q4"
      Redis__InstanceName: "L:Res:Bkg:"
      Redis__SlidingExpirationInSecond: "3600"
      MessageQueueSettings__QueueType: "RabbitMq"
      MessageQueueSettings__RabbitMqOptions__Url: "amqp://liberty-batch-rabbitmq"
      MessageQueueSettings__RabbitMqOptions__UserName: "guest"
      MessageQueueSettings__RabbitMqOptions__Password: "guest"
      Services__BatchSchedulerService__Url: "http://liberty-batch-scheduler:3144"
      Services__BatchSchedulerService__AccessCode: "01JAPEP5KQ5E7B0TDSD47YR7ZS"
      MailTemplate__ApplicationName: "Plan Reservation System. Liberty co,.ltd"
      MailTemplate__ManagerURL: "http://fe.manager.local.com/reservation/detail/{id}?facilityCode={facilityCode}"
      MailTemplate__UserURL: "http://fe.user.local.com/booking-history/edit/{id}"
      MailTemplate__GuestURL: "http://fe.user.local.com/guest/{guestCode}"
    restart: always
    ports:
      - "3013:3013"
      # - "13013:13013"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 512M
    networks:
      - liberty-system
    depends_on:
      - liberty-reservation-db
      - liberty-reservation-db-migration
      - liberty-reservation-redis
      - liberty-reservation-seq

volumes:
  liberty-db-data:
  liberty-seq-data:
  liberty-minio-data:

networks:
  liberty-system:
    name: liberty-system-network
