syntax = "proto3";

package liberty.site.v1;

option csharp_namespace = "Liberty.Protobuf.Site.V1";

import "site_model.proto";

message PongProtoReply {
  string message = 1;
}

message GetFacilitySiteProtoReply {
  string code = 1;
  optional string name = 2;
  optional string description = 3;
  bool isOnLinePayment = 4;
  bool isOnSidePayment = 5;
  bool useDailyPerson = 6;
  bool canAddRoomOnModify = 7;
  optional string postcode = 8;
  optional string url = 9;
  optional FileOfBookingProtoModel file = 10;
  optional SiteOfBookingFacilityProtoModel site = 11;
  repeated PersonAgeTypeOfBookingFacilityProtoModel personAgeTypes = 12;
  optional string heading = 13;
  bool isBarrierFree = 14;
  optional string barrierFreeInfoComment = 15;
  optional string email = 16;
  optional bool useSpaTax = 17;
  optional string spaTaxComment = 18;
  optional string spaTaxTable = 19;
  optional string logo = 20;
  optional string address1 = 21;
  optional string address2 = 22;
  optional string address3 = 23;
  optional string address4 = 24;
}

message SearchBookingByPlanProtoReply {
  repeated HeaderValueProtoModel headers = 1;
  repeated BookingSearchByPlanProtoModel data = 2;
}
