namespace Liberty.Reservation.Site.Application.Domains.Services.Interfaces;

public interface IReservationRoomGroupAppDateOptionItemService : IBaseServiceRelation<ReservationRoomGroupAppDateOptionItem>;
