<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.Media\Liberty.Media.csproj" />
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.SysIntegrationEvent\Liberty.SysIntegrationEvent.csproj" />
    <ProjectReference Include="..\..\..\modules\Liberty.Reservation.Application\Liberty.Reservation.Application.csproj" />
    <ProjectReference Include="..\Liberty.Reservation.Site.Application\Liberty.Reservation.Site.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localizes\Resources\Errors\I18n.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>I18n.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizes\Resources\I18n.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>I18n.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizes\Resources\Errors\I18n.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>I18n.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localizes\Resources\I18n.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>I18n.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Remove="Localizes\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Localizes\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Localizes\**" />
  </ItemGroup>

</Project>
