name: .NET 🧪 Build & Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'

jobs:
  build:
    runs-on: codebuild-github-action-runner-liberty-membership-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      DOTNET_INSTALL_DIR: $HOME/.dotnet

    steps:
      - name: 📥 Checkout source with submodules
        uses: actions/checkout@v4

        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive

      - name: 🧰 Setup .NET SDK 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: 📦 Verify .NET installation
        run: dotnet --info

      - name: 📦 Restore dependencies
        run: dotnet restore Liberty.Application.slnf

      - name: 🛠️ Build solution
        run: dotnet build Liberty.Application.slnf --no-restore --tl --no-incremental -warnaserror -maxcpucount:2
