global using Asp.Versioning;
global using AutoMapper;
global using FluentValidation;
global using Liberty.Pagination;
global using Liberty.Reservation.Application.Cqrs.BaseQueries;
global using MediatR;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
