services:
  platform-kernel-db:
    container_name: platform-kernel-db
    image: postgres:13
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: platform-kernel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01j6efde8q4q48crxe93crwxkc
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "8432:5432"
    networks:
      - platform-kernel
    deploy:
      mode: replicated
      replicas: 1

networks:
  platform-kernel:
    name: platform-kernel-network
