<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.Hangfire\Liberty.Hangfire.csproj" />
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.SysIntegrationEvent\Liberty.SysIntegrationEvent.csproj" />
  </ItemGroup>

</Project>
