namespace Liberty.Reservation.Site.Application.Domains.Services.Interfaces;

public interface IReservationRoomGroupAppDatePersonAgeTypeService : IBaseServiceRelation<ReservationRoomGroupAppDatePersonAgeType>;
