<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <IsPackable>false</IsPackable>
    <UserSecretsId>2230ccfc-9d20-4fd6-be07-af86ba430314</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.2.0" />
    <PackageReference Include="Aspire.Hosting.MySql" Version="8.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\services\employee\Liberty.Reservation.Employee.WebAPI\Liberty.Reservation.Employee.WebAPI.csproj" />
  </ItemGroup>

</Project>
