using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

string? vulnerableJsonPath = null;
string? outdatedJsonPath = null;
string? outputPath = null;
string? solutionName = null;

for (var i = 0; i < args.Length; i++)
{
    switch (args[i])
    {
        case "--vulnerable-json":
            vulnerableJsonPath = args[++i];
            break;
        case "--outdated-json":
            outdatedJsonPath = args[++i];
            break;
        case "--output":
            outputPath = args[++i];
            break;
        case "--solution":
            solutionName = args[++i];
            break;
    }
}

if (string.IsNullOrWhiteSpace(vulnerableJsonPath) || string.IsNullOrWhiteSpace(outdatedJsonPath))
{
    await Console.Error.WriteLineAsync(
        "Usage: --vulnerable-json <file> --outdated-json <file> [--solution <name>] --output <file>"
    );
    return 2;
}

outputPath ??= $"dependency-audit-{DateTime.Now:yyyy-MM-dd}.md";
solutionName ??= DetectSolutionName() ?? "Unknown";

var options = new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true,
    ReadCommentHandling = JsonCommentHandling.Skip,
    AllowTrailingCommas = true
};

VulnerableRoot? vulnRoot;
OutdatedRoot? outRoot;

await using (var fs = File.OpenRead(vulnerableJsonPath))
{
    vulnRoot = await JsonSerializer.DeserializeAsync<VulnerableRoot>(fs, options);
}

await using (var fs = File.OpenRead(outdatedJsonPath))
{
    outRoot = await JsonSerializer.DeserializeAsync<OutdatedRoot>(fs, options);
}

var vulnerabilities = AggregateVulnerabilities(vulnRoot);
var updates = AggregateUpdates(outRoot);

var (majors, nonMajors) = SplitMajorUpdates(updates);

var md = new StringBuilder();
md.AppendLine($"# Dependency Audit Report — {DateTime.Now:yyyy-MM-dd}");
md.AppendLine();
md.AppendLine("This report was generated by scripts/dependency-audit.sh.");
md.AppendLine();
md.AppendLine("- Managers detected: NuGet (.NET)");
md.AppendLine($"- Solution: {solutionName}");
md.AppendLine(
    "- Note on \"fixed versions\": For each vulnerable package, refer to the advisory link for the exact fixed version(s). The \"Latest\" versions in the updates section indicate the most recent stable available and may include fixes."
);
md.AppendLine(
    "- Policy: Major upgrades are flagged as potential breaking changes and should be batched or skipped by default pending review."
);
md.AppendLine();

// Major updates first as summary of potential breaking changes
md.AppendLine("## Summary of Potential Breaking Changes (Major Updates)");
md.AppendLine();
if (majors.Count == 0)
{
    md.AppendLine("No major updates available.");
}
else
{
    md.AppendLine("| Package | Resolved | Latest | Change | Note |");
    md.AppendLine("|---|---:|---:|---:|---|");
    foreach (var u in majors.OrderBy(u => u.Package))
    {
        md.AppendLine(
            $"| {u.Package} | {u.Resolved} | {u.Latest} | MAJOR | Potential breaking change — consider batching/skipping by default |"
        );
    }
}

md.AppendLine();

// Vulnerabilities section
md.AppendLine("## Vulnerabilities");
md.AppendLine();
if (vulnerabilities.Count == 0)
{
    md.AppendLine("No known vulnerabilities found by dotnet list (including transitive).");
}
else
{
    md.AppendLine("| Package | Affected Version(s) | Severity | Advisory ID | Advisory URL |");
    md.AppendLine("|---|---|---|---|---|");
    foreach (var v in vulnerabilities.OrderByDescending(v => SeverityRank(v.Severity)).ThenBy(v => v.Package))
    {
        md.AppendLine($"| {v.Package} | {v.ResolvedVersion} | {v.Severity} | {v.AdvisoryId} | {v.AdvisoryUrl} |");
    }
}

md.AppendLine();

// Updates section
md.AppendLine("## Available Updates (Patch/Minor)");
md.AppendLine();
if (nonMajors.Count == 0)
{
    md.AppendLine("No patch/minor updates available.");
}
else
{
    md.AppendLine("| Package | Resolved | Latest | Change |");
    md.AppendLine("|---|---:|---:|---|");
    foreach (var u in nonMajors.OrderBy(u => u.Package))
    {
        md.AppendLine($"| {u.Package} | {u.Resolved} | {u.Latest} | {u.ChangeType} |");
    }
}

md.AppendLine();

md.AppendLine("---");
md.AppendLine(
    "Action: I can attempt to apply patch/minor updates automatically and run the test suite. Would you like me to proceed? Reply 'yes' to proceed or 'no' to skip."
);

await File.WriteAllTextAsync(outputPath, md.ToString());
Console.WriteLine($"Wrote {outputPath}");
return 0;

static string? DetectSolutionName()
{
    var cwd = Directory.GetCurrentDirectory();
    var sln = Directory.EnumerateFiles(cwd, "*.sln", SearchOption.TopDirectoryOnly).FirstOrDefault();
    return sln is null ? null : Path.GetFileName(sln);
}

static List<VulnerabilityRow> AggregateVulnerabilities(
    VulnerableRoot? root
)
{
    var list = new List<VulnerabilityRow>();
    if (root?.Projects == null)
    {
        return list;
    }

    foreach (var proj in root.Projects)
    {
        if (proj.Frameworks == null)
        {
            continue;
        }

        foreach (var fw in proj.Frameworks)
        {
            if (fw.TopLevelPackages != null)
            {
                foreach (var p in fw.TopLevelPackages)
                {
                    AddPkg(p);
                }
            }

            if (fw.TransitivePackages != null)
            {
                foreach (var p in fw.TransitivePackages)
                {
                    AddPkg(p);
                }
            }

            continue;

            void AddPkg(
                PackageVuln? p
            )
            {
                if (p?.Vulnerabilities == null || p.Vulnerabilities.Count == 0)
                {
                    return;
                }

                foreach (var adv in p.Vulnerabilities)
                {
                    var (id, url) = ExtractAdvisory(adv.AdvisoryUrl);
                    list.Add(
                        new VulnerabilityRow
                        {
                            Package = p.Id ?? "",
                            ResolvedVersion = p.ResolvedVersion ?? "",
                            Severity = adv.Severity ?? "Unknown",
                            AdvisoryId = id,
                            AdvisoryUrl = url
                        }
                    );
                }
            }
        }
    }

    // Dedupe exact duplicates
    return list
        .DistinctBy(v => (v.Package, v.ResolvedVersion, v.Severity, v.AdvisoryId))
        .ToList();
}

static (string AdvisoryId, string AdvisoryUrl) ExtractAdvisory(
    string? url
)
{
    if (string.IsNullOrWhiteSpace(url))
    {
        return ("", "");
    }

    var m = Regex.Match(url, @"advisories/([^/]+)$", RegexOptions.IgnoreCase);
    return m.Success ? (m.Groups[1].Value, url) : ("", url);
}

static List<UpdateRow> AggregateUpdates(
    OutdatedRoot? root
)
{
    var map = new Dictionary<string, (string Resolved, string Latest)>(StringComparer.OrdinalIgnoreCase);
    if (root?.Projects == null)
    {
        return [];
    }

    foreach (var proj in root.Projects)
    {
        if (proj.Frameworks == null)
        {
            continue;
        }

        foreach (var fw in proj.Frameworks)
        {
            if (fw.TopLevelPackages != null)
            {
                foreach (
                    var p in fw.TopLevelPackages.Where(
                        p => !string.IsNullOrWhiteSpace(p.Id)
                            && !string.IsNullOrWhiteSpace(p.ResolvedVersion)
                            && !string.IsNullOrWhiteSpace(p.LatestVersion)
                    )
                )
                {
                    Upsert(map, p.Id!, p.ResolvedVersion!, p.LatestVersion!);
                }
            }

            if (fw.TransitivePackages == null)
            {
                continue;
            }

            foreach (
                var p in fw.TransitivePackages.Where(
                    p => !string.IsNullOrWhiteSpace(p.Id)
                        && !string.IsNullOrWhiteSpace(p.ResolvedVersion)
                        && !string.IsNullOrWhiteSpace(p.LatestVersion)
                )
            )
            {
                Upsert(map, p.Id!, p.ResolvedVersion!, p.LatestVersion!);
            }
        }
    }

    var list = new List<UpdateRow>();
    foreach (var kv in map)
    {
        var (change, isChange) = ClassifyChange(kv.Value.Resolved, kv.Value.Latest);
        if (!isChange)
        {
            continue;
        }

        list.Add(
            new UpdateRow
            {
                Package = kv.Key,
                Resolved = kv.Value.Resolved,
                Latest = kv.Value.Latest,
                ChangeType = change
            }
        );
    }

    return list
        .DistinctBy(u => (u.Package, u.Resolved, u.Latest, u.ChangeType))
        .ToList();
}

static void Upsert(
    Dictionary<string, (string Resolved, string Latest)> map,
    string id,
    string resolved,
    string latest
)
{
    if (!map.TryGetValue(id, out var cur))
    {
        map[id] = (resolved, latest);
        return;
    }

    // Prefer the highest latest and highest resolved we see
    var bestResolved = MaxVersion(cur.Resolved, resolved);
    var bestLatest = MaxVersion(cur.Latest, latest);
    map[id] = (bestResolved, bestLatest);
}

static string MaxVersion(
    string a,
    string b
)
{
    var cmp = CompareVersions(a, b);
    return cmp >= 0 ? a : b;
}

static (string Change, bool IsChange) ClassifyChange(
    string resolved,
    string latest
)
{
    var r = ParseVersion(resolved);
    var l = ParseVersion(latest);
    if (r == null || l == null)
    {
        return ("unknown", !string.Equals(resolved, latest, StringComparison.OrdinalIgnoreCase));
    }

    var rv = r.Value;
    var lv = l.Value;
    if (lv.Major > rv.Major)
    {
        return ("MAJOR", true);
    }

    if (lv.Major < rv.Major)
    {
        return ("downgrade", false);
    }

    if (lv.Minor > rv.Minor)
    {
        return ("minor/patch", true);
    }

    if (lv.Minor < rv.Minor)
    {
        return ("downgrade", false);
    }

    if (lv.Patch > rv.Patch)
    {
        return ("minor/patch", true);
    }

    if (lv.Patch < rv.Patch)
    {
        return ("downgrade", false);
    }

    // Build/Rev ignored
    return ("none", false);
}

static int CompareVersions(
    string a,
    string b
)
{
    var va = ParseVersion(a);
    var vb = ParseVersion(b);
    switch (va)
    {
        case null when vb == null:
            return 0;
        case null:
            return -1;
    }

    if (vb == null)
    {
        return 1;
    }

    var av = va.Value;
    var bv = vb.Value;
    var c = av.Major.CompareTo(bv.Major);
    if (c != 0)
    {
        return c;
    }

    c = av.Minor.CompareTo(bv.Minor);
    if (c != 0)
    {
        return c;
    }

    c = av.Patch.CompareTo(bv.Patch);
    return c != 0 ? c : 0;
}

static (int Major, int Minor, int Patch)? ParseVersion(
    string v
)
{
    if (string.IsNullOrWhiteSpace(v))
    {
        return null;
    }

    // Strip prerelease/build metadata
    var core = v.Split('-', '+')[0];
    var parts = core.Split('.');
    var nums = new[] { 0, 0, 0 };
    for (var i = 0; i < Math.Min(3, parts.Length); i++)
    {
        if (!int.TryParse(parts[i], out nums[i]))
        {
            nums[i] = 0;
        }
    }

    return (nums[0], nums[1], nums[2]);
}

static (List<UpdateRow> Majors, List<UpdateRow> NonMajors) SplitMajorUpdates(
    List<UpdateRow> updates
)
{
    var majors = updates.Where(u => string.Equals(u.ChangeType, "MAJOR", StringComparison.OrdinalIgnoreCase)).ToList();
    var nonMajors = updates.Where(u => !string.Equals(u.ChangeType, "MAJOR", StringComparison.OrdinalIgnoreCase)).ToList();
    return (majors, nonMajors);
}

static int SeverityRank(
    string? s
)
{
    return (s ?? string.Empty).ToLowerInvariant() switch
    {
        "critical" => 4,
        "high" => 3,
        "moderate" => 2,
        "low" => 1,
        _ => 0
    };
}

internal record VulnerableRoot(
    [property: JsonPropertyName("projects")]
    List<VulnProject>? Projects
);

internal record VulnProject(
    [property: JsonPropertyName("path")] string? Path,
    [property: JsonPropertyName("frameworks")]
    List<VulnFramework>? Frameworks
);

internal record VulnFramework(
    [property: JsonPropertyName("framework")]
    string? Framework,
    [property: JsonPropertyName("topLevelPackages")]
    List<PackageVuln>? TopLevelPackages,
    [property: JsonPropertyName("transitivePackages")]
    List<PackageVuln>? TransitivePackages
);

internal record PackageVuln(
    [property: JsonPropertyName("id")] string? Id,
    [property: JsonPropertyName("resolvedVersion")]
    string? ResolvedVersion,
    [property: JsonPropertyName("vulnerabilities")]
    List<Advisory>? Vulnerabilities
);

internal record Advisory(
    [property: JsonPropertyName("severity")]
    string? Severity,
    [property: JsonPropertyName("advisoryurl")]
    string? AdvisoryUrl
);

internal class VulnerabilityRow
{
    public string Package { get; set; } = string.Empty;
    public string ResolvedVersion { get; set; } = string.Empty;
    public string Severity { get; set; } = string.Empty;
    public string AdvisoryId { get; set; } = string.Empty;
    public string AdvisoryUrl { get; set; } = string.Empty;
}

internal record OutdatedRoot(
    [property: JsonPropertyName("projects")]
    List<OutProject>? Projects
);

internal record OutProject(
    [property: JsonPropertyName("path")] string? Path,
    [property: JsonPropertyName("frameworks")]
    List<OutFramework>? Frameworks
);

internal record OutFramework(
    [property: JsonPropertyName("framework")]
    string? Framework,
    [property: JsonPropertyName("topLevelPackages")]
    List<PackageOutdated>? TopLevelPackages,
    [property: JsonPropertyName("transitivePackages")]
    List<PackageOutdated>? TransitivePackages
);

internal record PackageOutdated(
    [property: JsonPropertyName("id")] string? Id,
    [property: JsonPropertyName("requestedVersion")]
    string? RequestedVersion,
    [property: JsonPropertyName("resolvedVersion")]
    string? ResolvedVersion,
    [property: JsonPropertyName("latestVersion")]
    string? LatestVersion
);

internal class UpdateRow
{
    public string Package { get; set; } = string.Empty;
    public string Resolved { get; set; } = string.Empty;
    public string Latest { get; set; } = string.Empty;
    public string ChangeType { get; set; } = string.Empty;
}
