services:
  liberty-reservation-lab-db:
    container_name: liberty-reservation-lab-db
    image: postgres:13
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: liberty_reservation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01j6efde8q4q48crxe93crwxkc
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "8432:5432"
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1

  liberty-facility-lab-db:
    container_name: liberty-facility-lab-db
    image: postgres:13
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: liberty_facility
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "9432:5432"
    networks:
      - liberty-system
    deploy:
      mode: replicated
      replicas: 1

networks:
  liberty-system:
    name: liberty-system-network
