using AutoMapper;
using MediatR;
using PlatformKernel.ApplicationShared.Cqrs.BaseCommand;
using PlatformKernel.Service.Base.Application.AuditEvents;
using PlatformKernel.UnitOfWork.Abstractions;

namespace PlatformKernel.Service.Base.Application.Cqrs.BaseCommands;

/// <summary>
/// Represents an abstract base class for handling commands with a specific response type.
/// Provides a foundation for managing dependencies and executing command logic, while also enabling
/// features such as cache management and event dispatching.
/// </summary>
/// <typeparam name="TCommand">The type of the command being processed, which must implement <see cref="ICommandBase{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response generated by the command processing.</typeparam>
public abstract class CommandBaseWithAuditEventHandler<TCommand, TResponse>(
    IUnitOfWork unitOfWork,
    IMapper mapper,
    IMediator mediator
) : CommandBaseHandler<TCommand, TResponse>(unitOfWork, mapper)
    where TCommand : ICommandBase<TResponse>
{
    protected IMediator Mediator { get; } = mediator;

    /// <summary>
    /// Represents event-specific data associated with a command handler's processing.
    /// </summary>
    protected IAuditEventData? AuditEventData { get; set; }

    /// <summary>
    /// Processes the specified command request, executes the associated business logic, and manages post-processing tasks such as cache removal.
    /// </summary>
    /// <param name="request">The command request containing the details required for processing.</param>
    /// <param name="cancellationToken">A token that can be used to signal the cancellation of the operation.</param>
    /// <returns>A task representing the asynchronous handling process. The task's result is the response produced by the execution of the command logic.</returns>
    public override async Task<TResponse> Handle(
        TCommand request,
        CancellationToken cancellationToken
    )
    {
        var response = await base.Handle(request, cancellationToken);

        if (AuditEventData is not null)
        {
            await SendEvent(
                request,
                response,
                AuditEventData,
                CancellationToken.None
            );
        }

        return response;
    }

    /// <summary>
    /// Sends an event associated with the command execution process.
    /// </summary>
    /// <param name="request">The command request that was processed.</param>
    /// <param name="response">The response generated as a result of processing the command.</param>
    /// <param name="eventData">The event-specific data that provides additional context or information for the event handling logic.</param>
    /// <param name="cancellationToken"></param>
    protected virtual async Task SendEvent(
        TCommand request,
        TResponse response,
        IAuditEventData eventData,
        CancellationToken cancellationToken = default
    )
    {
        await Mediator.Publish(eventData, cancellationToken);
    }
}

/// <summary>
/// Represents a base class for handling create commands and returning a response.
/// </summary>
/// <typeparam name="TCommand">The type of the create command being handled. Must implement <see cref="ICommandBase{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response returned after processing the create command.</typeparam>
public abstract class CreateCommandWithAuditEventHandlerBase<TCommand, TResponse>(
    IUnitOfWork unitOfWork,
    IMapper mapper,
    IMediator mediator
) : CommandBaseWithAuditEventHandler<TCommand, TResponse>(
        unitOfWork,
        mapper,
        mediator
    ),
    ICreateCommandHandlerBase<TCommand, TResponse>
    where TCommand : ICommandBase<TResponse>;

/// <summary>
/// Represents a base class for handling update commands in a CQRS pattern.
/// </summary>
/// <typeparam name="TCommand">The type of the command to be handled. Must implement <see cref="ICommandBase{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response returned by the command handler.</typeparam>
public abstract class UpdateCommandWithAuditEventHandlerBase<TCommand, TResponse>(
    IUnitOfWork unitOfWork,
    IMapper mapper,
    IMediator mediator
) : CommandBaseWithAuditEventHandler<TCommand, TResponse>(
        unitOfWork,
        mapper,
        mediator
    ),
    IUpdateCommandHandlerBase<TCommand, TResponse>
    where TCommand : ICommandBase<TResponse>;

/// <summary>
/// Represents a base command handler for processing delete commands within the application.
/// </summary>
/// <typeparam name="TCommand">The type of the delete command to be handled. Must implement <see cref="ICommandBase{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the result produced by the delete command handler.</typeparam>
public abstract class DeleteCommandWithAuditEventHandlerBase<TCommand, TResponse>(
    IUnitOfWork unitOfWork,
    IMapper mapper,
    IMediator mediator
) : CommandBaseWithAuditEventHandler<TCommand, TResponse>(
        unitOfWork,
        mapper,
        mediator
    ),
    IDeleteCommandHandlerBase<TCommand, TResponse>
    where TCommand : ICommandBase<TResponse>;

/// <summary>
/// Represents the base class for handling action commands that do not return a result or involve modifying state.
/// </summary>
/// <typeparam name="TCommand">The type of the command being handled. Must implement <see cref="ICommandBase{TResponse}"/>.</typeparam>
/// <typeparam name="TResponse">The type of the response returned by the command handler.</typeparam>
public abstract class ActionCommandWithAuditEventHandlerBase<TCommand, TResponse>(
    IUnitOfWork unitOfWork,
    IMapper mapper,
    IMediator mediator
) : CommandBaseWithAuditEventHandler<TCommand, TResponse>(
        unitOfWork,
        mapper,
        mediator
    ),
    IActionCommandHandlerBase<TCommand, TResponse>
    where TCommand : ICommandBase<TResponse>;
