<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>BlueprintNormal.Infrastructure</RootNamespace>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="Serilog" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BlueprintNormal.Domain\BlueprintNormal.Domain.csproj" />
        <ProjectReference Include="..\BlueprintNormal.Dto\BlueprintNormal.Dto.csproj" />
        <ProjectReference Include="..\BlueprintNormal.Crosscutting\BlueprintNormal.Crosscutting.csproj" />
    </ItemGroup>

</Project>
