<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contexts\Configurations\**" />
    <EmbeddedResource Remove="Contexts\Configurations\**" />
    <None Remove="Contexts\Configurations\**" />
    <Compile Remove="Domains\Services\BookingCalendarPriceService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\liberty-asp\Liberty.ApplicationShared\Liberty.ApplicationShared.csproj" />
    <ProjectReference Include="..\..\..\modules\Liberty.Reservation.Application\Liberty.Reservation.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Requests\" />
  </ItemGroup>

</Project>
